name: release
    
on:
  push:
    tags:
      - "1.*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  cocos2dx-build-ios:
    name: "Release for iOS"
    runs-on: "macos-latest"
    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${{ github.ref }}"

      - name: Echo build progress
        run: echo "Kirikiroid2_${{ steps.extract_tag.outputs.tag }}.ipa build progress"

      - name: Set Python 2.7 as default
        run: |
          echo "alias python=python2.7" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install pyenv
        run: |
          brew update
          brew install pyenv

      - name: Install Python 2.7
        run: |
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
          echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
          source ~/.bash_profile
          pyenv install 2.7
          pyenv global 2.7
          python --version
          git clone https://github.com/cocos2d/cocos2d-x.git
          cd cocos2d-x
          git checkout tags/cocos2d-x-3.6
          yes | python download-deps.py
          git submodule update --init
          yes | python setup.py
          cd ..
       
      - name: Create new cocos2dx project
        run: |
          cd cocos2d-x
          ./setup.py
          source FILE_TO_SAVE_SYSTEM_VARIABLE
          cocos new MyCocosProject -l cpp -d ./


      - name: Generate Xcode project
        run: |
          cd cocos2d-x
          ./setup.py
          source FILE_TO_SAVE_SYSTEM_VARIABLE
          cocos gen-libs -p ios -m release

      - name: Build IPA
        run: |
          cd MyCocosProject
          xcodebuild -workspace MyCocosProject.xcworkspace -scheme MyCocosProject -configuration Release -destination generic/platform=iOS -archivePath build/MyCocosProject.xcarchive archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath build/MyCocosProject.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

      - name: Create IPA
        run: |
          mv build/MyCocosProject.ipa build/Kirikiroid2_${{ steps.extract_tag.outputs.tag }}_no_sign.ipa

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios_outputs
          path: build/Kirikiroid2_*.ipa
